title: Sentimental documentation
author: Marco Gordillo
email: marcopgordillo@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is a description about my blog. My blog is about IT
  and the impact in society. About how IT help people.
# social links
twitter_username: marcopgordillo
github_username:  marcopgordillo

show_excerpts: false # set to false to remove excerpts on the homepage
theme: jekyll-theme-minimal
permalink: pretty
hightlighter: rogue
social_links:
    twitter: jekyllrb
    github:  jekyll
    rss: rss

plugins:
 - jekyll-feed
 - jekyll-seo-tag

header_pages:
 - about.md